terraform-ibm-modules/stack-ibm-core-security-services

- .catalog-onboard-pipeline.yaml
- .releaserc
- catalogValidationValues.json.template
onboard repo to catalog pipeline
```
/run pipeline
```
> ci: onboard repo to catalog pipeline

- ibm_catalog.json
Update flavor name in ibm_catalog.json:
- Standard -> standard
```
/run pipeline
```
> Update flavor name in ibm_catalog.json

- reference-architectures/reference-architecture-css.md
Update meta-data that is used to generate link in clouddocs
```
/run pipeline
```
> Update meta-data that is used to generate link in clouddocs

- ibm_catalog.json
> fix: update default from of `resource_group_name` to `__NULL__`

- stack_definition.json
https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/34
https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/issues/40
```
/run pipeline
```
> feat: update names of the stacks

- ibm_catalog.json
- stack_definition.json
Expose `en_email_list` variable and update VLs
```
/run pipeline
```
> Expose `en_email_list` variable and update VLs

- ibm_catalog.json
- stack_definition.json
add outputs of services
Add outputs of the crns of various services created in the stack.
```
/run pipeline
```
> feat: add outputs of services

- catalogValidationValues.json.template
- ibm_catalog.json
- stack_definition.json
- tests/pr_test.go
Use existing resource group + add COS member later
```
/run pipeline
```
> Use existing resource group + add COS member layer

- ibm_catalog.json
- stack_definition.json
Stack Variable Cleanup
```
/run pipeline
```
> fix: variable cleanup

- ibm_catalog.json
update short and long descriptions
```
/run pipeline
```
> update short and long descriptions

- reference-architectures/reference-architecture-css.md
existing metadata is for docs-only reference architecture
```
/run pipeline
```
> update subcollection in ref architecture

- ibm_catalog.json
added `offering_docs_url` and `release_notes_url` to ibm_catalog.json
```
/run pipeline
```
> added `offering_docs_url` and `release_notes_url` to ibm_catalog.json

- ibm_catalog.json
> Add `ibm_created` tag to tile

- ibm_catalog.json
- stack_definition.json
update sm da to latest version.
update sm da to latest version.
```
/run pipeline
```
> feat: update sm version locator

- ibm_catalog.json
Changes already made directly in partner centre, but making here too for consistency:
```
/run pipeline
```
> Update ibm_catalog.json with `support_details`

- stack_definition.json
> fix: add url encoding to refs

- stack_definition.json
Reverts terraform-ibm-modules/stack-ibm-core-security-services#75 - the issue was fixed in production by projects service
> Revert "fix: add url encoding to refs"

- stack_definition.json
- tests/go.mod
- tests/go.sum
- tests/pr_test.go
```
[subprocess - update_stack_definition.py] INFO: Updating 1a - Key management
[subprocess - update_stack_definition.py] INFO: current version: v4.14.0
[subprocess - update_stack_definition.py] INFO: latest version: v4.15.0
[subprocess - update_stack_definition.py] INFO: latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.650ff7c9-5a41-4d32-a0db-6720ff56a016-global
[subprocess - update_stack_definition.py] INFO: Updating 1a - Key management to version v4.15.0
[subprocess - update_stack_definition.py] 
[subprocess - update_stack_definition.py] INFO: Updating 1b - Object storage
[subprocess - update_stack_definition.py] INFO: current version: v8.5.0
[subprocess - update_stack_definition.py] INFO: latest version: v8.8.4
[subprocess - update_stack_definition.py] INFO: latest …
```
> fix(deps): Update stack definition member versions

- reference-architectures/reference-architecture-css.md
Update name to IBM Cloud Essential Security and Observability Services to match catalog
```
/run pipeline
```
> Update name in reference architecture

- reference-architectures/reference-architecture-css.md
Update reference architecture metadata for version 1.3.1 of the stack.
```
/run pipeline
```
> Update ref arch to 1.3.1

- reference-architectures/reference-architecture-css.md
v1.4.1 is now the latest version publicly available
```
/run pipeline
```
> Update reference-architecture-css.md for v1.4.1

- stack_definition.json
> fixed bug where inputs were used on incorrect DA

- stack_definition.json
- The SCC DA in version 1.4.1 of the stack does a daily scan. However the latest SCC DA defaults to Monthly. Because of this, terraform tries to do an update in place, however it fails due to this provider bug: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5718
- The fix for now is to lock the scan back to daily in the stack definition so no update is required
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation …
> lock the SCC schedule to `daily` to workaround provider bug
